### ISSUE TITLE
problem with autocomple-java on windows.

### ISSUE THREAD

**Issue by Eider3a** [keskiju/autocomplete-java#23]
Hi, someone can help me, I have the next problem with Autocomplete-java:
autocomplete-java: Error: ENOENT: no such file or directory,
open 'C:\Users\Eider\Desktop\cursojava*'
here in this folder i have my files (.class and .java).
I was working in windows 8.1.
Thanks.

**Comment by keskiju** [comment]
There is probably something wrong with your classpath. What are contents of your .classpath file? Is it located in C:\Users\Eider\Desktop\cursojava\.classpath? 

If C:\Users\Eider\Desktop\cursojava is your project root directory and your java package hierarchy containing java and class files is directly underneath it, then your .classpath file contents should be:

```
.
```

Or alternatively

```
C:\Users\Eider\Desktop\cursojava
```

**Comment by Eider3a** [comment]
I have the file .classpath in the folder C:\Users\Eider\Desktop\cursojava and this file contains the path C:\Users\Eider\Desktop\cursojava that is where are my class and java files. it appears the same mistake when I open any file java.

**Comment by keskiju** [comment]
Sorry, I can't reproduce this on Windows 8.1, Atom 1.3.3 and autocomplete-java 0.11.0. I created folder C:\Users\jukka\Desktop\cursojava that contains:

```
test\Test.java
test\Test.class
test\app\Test2.java
test\app\Test2.class
.classpath
```

Contents of the .classpath file:

```
C:\Users\jukka\Desktop\cursojava
```

I open folder C:\Users\jukka\Desktop\cursojava with Atom editor and autocomplete works ok.

**Comment by keskiju** [comment]
Works ok now?

**Comment by Eider3a** [comment]
The error no longer appears when I open a file .java, but the java plugin does not working, I tried to reinstall the plugin but still does not work.

**Comment by keskiju** [comment]
Please update the autocomplete-java package and then check autocomplete-java messages from your console log while you open a java file (View -> Developer -> Toggle developer tools).
