### ISSUE TITLE
Command failed: /bin/sh -c "jar" ...

### ISSUE THREAD

**Issue by ghost** [keskiju/autocomplete-java#26]
Here, the complete error notification:
**autocomplete-java: Error: Command failed: /bin/sh -c "jar" tf "/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/rt.jar" /bin/sh: 1: jar: not found**

I don't understand... the package don't find Java ?

My classpath: ./src

**Comment by keskiju** [comment]
Have you set the JAVA_HOME environment variable or are java tools (jar, javap) on your path? Did you start Atom from command line? If you did not, Atom might not see the environment variables (JAVA_HOME, PATH) that you have set.

**Comment by ghost** [comment]
How to do ?
I have set path of JDK (JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64) in the "/etc/environment" file, but It don't work...

**Comment by keskiju** [comment]
If you use Linux: http://stackoverflow.com/questions/6477415/how-to-set-oracles-java-as-the-default-java-in-ubuntu. Also try relogin or reboot after you have set the environment variable.

On OS X the /etc/environment is no longer in use: http://apple.stackexchange.com/questions/107787/how-to-set-system-wide-environment-variables-on-os-x-mavericks. Try starting Atom from command line.

**Comment by ghost** [comment]
I wrote "export JAVA_HOME=/usr/lib/jvm/default-java" at the end of the file ".bashrc" but It don't work...
Atom show me the same error...

**Comment by keskiju** [comment]
.bashrc works only for bash, I think. Try relogin and then run "atom" from command line (bash).

/etc/environment is global but requires restart. Did you restart your computer after you set JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64 in /etc/environment?

**Comment by ghost** [comment]
Don't work for your two ways.
But I have a new error:
**autocomplete-java: Error: Command failed: /bin/sh -c "/usr/lib/jvm/java-7-openjdk-amd64/bin/jar" tf "/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/rt.jar" /bin/sh: 1: /usr/lib/jvm/java-7-openjdk-amd64/bin/jar: not found**

When I look at "/usr/lib/jvm/java-7-openjdk-amd64/bin/jar", I don't see the file "jar"... It don't exist...

**Comment by keskiju** [comment]
Ok, now JAVA_HOME is set. Perhaps you have installed only the Java runtime enviroment (openjdk-7-jre). For development you need openjdk-7-jdk that contains javac, javap and jar tools.

**Comment by ghost** [comment]
Ahhhhh !
I thought that OpenJDK is the JDK... sorry ^^
Now, I don't have error.

Thanks ^^

NB: But, your autocompletion package don't work fine....
For example, with a String named "test", when I write "test." (test + dot), Atom don't show me the list of function for the String variable... :(

**Comment by keskiju** [comment]
Type determination is still just a quick hack. See notes in [autocomplete-java](https://atom.io/packages/autocomplete-java) and issue #8. Use classname (String.valueOf...) instead of variable when type determination fails.

**Comment by ghost** [comment]
Ok, Thank you :)
