### ISSUE TITLE
LB: Error reading .eslintrc

### ISSUE THREAD

**Issue by SlimeQ** [keskiju/autocomplete-java#30]
```
LB: Error reading .eslintrc at /home/quincy/.atom/packages/autocomplete-java/.eslintrc
Unexpected number
```

this one popped up when i opened up the autocomplete-java code in atom. latest update

**Comment by keskiju** [comment]
Yes, this appeared for me also after updating eslint to the latest version. I will check it out when I find the time.

**Comment by keskiju** [comment]
Problem has disappeared. Probably was caused by eslint bug.
