### ISSUE TITLE
inserting method from autocomplete doesn't place cursor correctly

### ISSUE THREAD

**Issue by SlimeQ** [keskiju/autocomplete-java#31]
when an autocomplete option is chosen, the cursor becomes invisible and the parameter class names are inserted (eg; java.lang.String). the cursor position stays where it was when enter was pressed. the expected behavior, imo, would be to place the cursor in the parameter field and be able to tab between them as if it were a snippet
![screenshot from 2016-01-18 13 46 32](https://cloud.githubusercontent.com/assets/3934698/12399779/f83ee31a-bde9-11e5-9238-af9118226a50.png)

**Comment by keskiju** [comment]
Yes, you can tab through variable name and parameters using tab. The cursor is not placed at the first parameter because after examining methods of a class, you are likely to change the class name to a variable name first and only then fill the parameters. e.g

```
CoreEntity.sortDescBy(java.lang.String)
```

becomes

```
myEntity.sortDescBy("some string");
```

But on my editor cursor does not stay where enter was pressed. The class name (here CoreEntity) becomes selected automatically so that I can replace it, and after that I can cycle through all parameters using tab replacing them also.

**Comment by SlimeQ** [comment]
ah, yeah upon further inspection i can tab through the fields. however the first field selected in that example is `CoreEntity` and i have to press tab to switch to `java.lang.String`. false alarm. it just occurred to me that the package only works on class names because variable names don't get registered to the proper type. this behavior makes sense now.

it would be neat if variable names could get resolved to classes, however. should be possible with a clever regex routine. if i were to try to implement this where would i find the hook that generates autocomplete possibilities for a given variable?

**Comment by keskiju** [comment]
Check issue #8. It already resolves a variable name to a class in some cases. You can see this in action in the preview animation shown on readme,md. But it's still a really quick hack so by all means improve it, if you like. You can see these TODO comments there:

```
    // Find class name by a variable name given as prefix
    // TODO traverse brackets backwards to match correct scope (with regexp)
    // TODO handle 'this.varName' correctly
```

**Comment by keskiju** [comment]
Currently it seeks variable declaration from previous 10 rows:

```
editor.getTextInRange([[bufferPosition.row - 10, 0], bufferPosition]),
```

Just remove that and include some bracket matching to the regex and it should work much better already.

**Comment by keskiju** [comment]
And also scopeDescriptor mentioned in issue #8 might provide some useful information about current scope.
