### ISSUE TITLE
Can't automatically add imports

### ISSUE THREAD

**Issue by dylanm312** [keskiju/autocomplete-java#34]
I'm not quite sure how to get this plugin to add imports for me automatically. I can do it manually through the right click -> get import -> paste method, but I can't seem to get the imports to add themselves automatically. Help?

**Comment by keskiju** [comment]
The "get import and paste" is a feature of java-importer package and it does not support automatic imports at all. But if you are asking help for autocomplete-java package, have you tried to follow all instructions in the usage section? The autocomplete-java package requires installed JDK, configured classpath and compiled class files.

**Comment by dylanm312** [comment]
I'm not sure I quite understand how to set up the .classpath file. The readme isn't very helpful regarding specifically how to set the file up.

**Comment by dylanm312** [comment]
I figured it out. Thanks for your help!
