### ISSUE TITLE
lodash not found

### ISSUE THREAD

**Issue by SlimeQ** [keskiju/autocomplete-java#37]
i just updated to 1.2.1 and got the old lodash error from #1

**Comment by noseglid** [comment]
I've noticed that updating packages sometimes fails to install dependencies (or it re-activates before deps are installed properly). Does it work if you uninstall/reinstall `autocomplete-java` ?

**Comment by keskiju** [comment]
You probably mean issue #33 :)

**Comment by keskiju** [comment]
Cleaning up old issues...
