### ISSUE TITLE
java rt.jar not found 

### ISSUE THREAD

**Issue by ZHANG-Quentin** [keskiju/autocomplete-java#47]
When I opened Atom today, I got a message warning: autocomplete-java: java rt.jar not found

But I didn't change any setting of my PC recently(i.e. JDK, JVM), that confuses me and I hate a red warning keeps showing up at the top right corner when I start up Atom every time.

Does anyone come across to this message before?

**Comment by keskiju** [comment]
Did you already figure this one out? Maybe you have updated your JDK and your JAVA_HOME points to an old location. See #49.

**Comment by ShueyYuen** [comment]
Update to JDK 12+,There is no need for JAVA_HOME, so it will also show a Warning.

**Comment by nileshteji** [comment]
Sir i am using java 12  and getting this error please help 
autocomplete-java: java rt.jar not found

**Comment by MrKleeblatt** [comment]
I had the same problem and didn't know what's going on... I downloaded autocomplete-java just a few hours ago but every other package does work.

I got the solution. You have to set the JAVA_HOME and the JRE_HOME environment variable. [Here is how you can do this](https://confluence.atlassian.com/doc/setting-the-java_home-variable-in-windows-8895.html)
And maybe your PATH environment variable isn't set right so just check it out...
