### ISSUE TITLE
Is this a severe bug?

### ISSUE THREAD

**Issue by ginger1995** [keskiju/autocomplete-java#48]
http://recordit.co/Ku2BfXpduM   Here you could see a screen recording I made.

When I tried to import some new modules or I just press shift+ctrl+alt+o to try to import, all the import lines will go inside the class...That's terrible.. Could you help me solve the issue? Thanks a lot!

**Comment by keskiju** [comment]
This is a known issue. All java source files usually contain a package declaration but you don't have one in your file. Add a package declaration or at least couple of empty lines at the beginning of java source file and it should work fine. Currently autocomplete-java does not support java files without package declaration.

**Comment by keskiju** [comment]
#35 duplicate

**Comment by ginger1995** [comment]
OK  I see  ,thanks~
