### ISSUE TITLE
can't find java rt.jar *windows 10 HOME, jdk  10.0.2-13, atom 1.30*

### ISSUE THREAD

**Issue by ghost** [keskiju/autocomplete-java#62]
Dear Sirs,

I'm a new java student at university in Sweden. I really want to try the autocomplete package but I get an error saying can't find java rt.jar.. What can I do?

**Comment by hanbing5210** [comment]
Dear Sirs,
I'm a java programmer in China . I find same problems with @adamberglund  and I try the old jdk ,the problem always excited.  I install two jdks in my OS.jdk 1.8.0_181 and jdk10

**Comment by AGBJRDev** [comment]
I get the same problem and literally just installed the Atom IDE. Reinstalling the package did nothing.

**Comment by keskiju** [comment]
This is duplicate with #58. Currently the autocomplete-java package does not support the latest JDK versions, because rt.jar was removed.
