### ISSUE TITLE
Error: autocomplete-java: java rt.jar not found

### ISSUE THREAD

**Issue by ghost** [keskiju/autocomplete-java#63]
I just install the package and it appears, autocomplete-java: java rt.jar not found
Windows 10 64bit

**Comment by milovangudelj** [comment]
I have the same problem even after installing the latest JDK (Java SE 12 - 19/03/2019) and setting the JAVA_HOME environement variable...

**Comment by keskiju** [comment]
This is duplicate with #58. Currently the autocomplete-java package does not support the latest JDK versions, because rt.jar was removed.
